### PR TITLE
Copper mountain S5048 driver

### PR DESCRIPTION
**Pull request by Saba-Mehshar**
This is the driver for copper mountain S5048 network analyzer. It can connect to the instrument, but not responding to the commands. Can anyone review it please? Many thanks.

### CODE REVIEW

**Comment by Saba-Mehshar** [comment]
Hi,
I have followed the HP 8753D Network Analyzer Qcodes driver script to write this driver, but have changed the SCPI commands as per the CMT S5048 programming manual.
I have been getting error with 305 & 306 lines because of this it does get failed to set the display format and am unable to update any parameters.

**Comment by jenshnielsen** [comment]
@Saba-Mehshar I think you are making it much more difficult for you trying to take an existing driver and modifying it. 
There are going to be a number of things that do not apply. I would recommend that you start with a minimal driver. 

E.g. start with the CMTS5048 class and add parameters to this one by one making sure that they work. You can take inspiration from the HP driver but coping and modifying it directly is unlikely to be successful

**Comment by Saba-Mehshar** [comment]
@jenshnielsen Thanks for the suggestion. This is what I did initially - I had started with a NetworkAnalyser_S5048 class and added all the parameters to it. Everything was working perfectly except that I was not able to save and plot the data. Then I thought of going for the HP 8753D VNA and its not working as well.
Okay, I will now do as you said - start with a CMTS5048 class, and then modify it.
Hope it works this time. Thanks again..

**Comment by Akshita07** [comment]
@Saba-Mehshar Have you been able to make the driver work? If you need any help do let us know.

**Comment by Saba-Mehshar** [comment]
Hi @Akshita07
Sorry for the late response. 
I had started with a class and added all the parameters to it and it was working fine. Then, I added a few more things to it but couldn't test it yet. I will update you when I go back to the lab and start working on it. Thank you very much for offering kind help!

**Comment by Akshita07** [comment]
Hello @Saba-Mehshar ,

Did you get a chance to test the new implementation? Do reach out for any help.

**Comment by erikawa-e** [comment]
Hi,
I think you can use M5180 driver:
https://github.com/QCoDeS/Qcodes_contrib_drivers/tree/master/qcodes_contrib_drivers/drivers/CopperMountain

I have Copper Mountain S5045 and it is working for me to some extent.
(I had to erase 
"assert isinstance(self.instrument, M5180)"
part in 
def get_raw
)
Make sure that you change the frequency/power ranges.

**Comment by astafan8** [comment]
@Saba-Mehshar @erikawa-e shall we proceed with this PR or not?

**Review by astafan8 — APPROVED** [review]

**Comment by astafan8** [comment]
@Saba-Mehshar @erikawa-e I fixed a few small things in the driver and will merge it. If you or other users find things to improve or fix, just open new PRs with that :) this driver will be part of 0.12.0 release of qcodes contrib drivers

**Comment by Saba-Mehshar** [comment]
@Mikhail Astafev<https://github.com/astafan8> @Akshita<https://github.com/Akshita07>Akshita<https://github.com/Akshita07> @Jens Hedegaard Nielsen<https://github.com/jenshnielsen> thanks very much for ​your help!




----------------------------------

Please feel free to reply during your own working hours if you receive my emails outside working hours.



Saba Khan

PhD Student



Low Temperature Physics

Department of Physics

Lancaster University

Bailrigg, Lancaster LA1 4YW, UK

________________________________
From: Mikhail Astafev ***@***.***>
Sent: 21 December 2021 01:11 PM
To: QCoDeS/Qcodes_contrib_drivers ***@***.***>
Cc: Khan, Saba (Postgrad Researcher) ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [QCoDeS/Qcodes_contrib_drivers] Copper mountain S5048 driver (#78)


This email originated outside the University. Check before clicking links or attachments.

@Saba-Mehshar<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSaba-Mehshar&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842774766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S4f3c3TEogjjEkfB1CaKuHQZLkamI3p9RptA1sbI0tg%3D&reserved=0> @erikawa-e<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ferikawa-e&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842784717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nO3GADZxy4jOQOKLaLEmiu28q1eJe5RUSavynm1tJBk%3D&reserved=0> I fixed a few small things in the driver and will merge it. If you or other users find things to improve or fix, just open new PRs with that :) this driver will be part of 0.12.0 release of qcodes contrib drivers

—
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FQCoDeS%2FQcodes_contrib_drivers%2Fpull%2F78%23issuecomment-998766846&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842794673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gWfGb5HxPmxJLnulGW8Qf%2FsyfaX5ZZzipqsCCINaB%2B8%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPYNBKDW4QUSY27GAPWGL6DUSB4HPANCNFSM4SGI3KZQ&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842794673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RqojYZoa96ll2z7JoHSbK5dW1ko4P3ZyqTgJp2gIJWc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842804629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZECAqdaATCZBtro7Cxs5XxVbmogE5X2kXiIRkCc2Zz0%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckhansm1%40live.lancs.ac.uk%7C10b0e7b3a9194c7d04eb08d9c4836322%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637756890842814585%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Voo4hYtg38o04Wft6zX8I9T0rH1QrQNznDItNSJx63c%3D&reserved=0>.

**Pull request merged**
