### PR TITLE
fix type checking with qcodes 019 and pyvisa 1.11

### PR DESCRIPTION
**Pull request by jenshnielsen**
@farbo this should get the ci to pass with the newest qcodes version

### CODE REVIEW

**Comment by FarBo** [comment]
Thanks @jenshnielsen

**Comment by jenshnielsen** [comment]
@farbo can you review and approve?

**Comment by FarBo** [comment]
@jenshnielsen 
Sure

**Comment by FarBo** [comment]
@jenshnielsen 
LGMT

**Review by FarBo — APPROVED** [review]

**Pull request merged**
