### PR TITLE
Drivers for Valon 5015 Frequency Synthesizer instrument

### PR DESCRIPTION
**Pull request by fedonman**
This PR: 

- Adds the `drivers/Valon/Valon_1505.py` file which contains the driver for the [Valon 5015](https://www.valonrf.com/5015-frequency-synthesizer-15ghz.html) Frequency Synthesizer instrument.
- Adds the `docs/examples/Valon_1505.ipynb` file which contains an example on how to use the driver.

Tests and sims are not implemented, but the driver has been tested manually in the lab.

### CODE REVIEW

**Review by AlbertMitjans — APPROVED** [review]
Amazing!! Can you add this driver in the `__init__` of the drivers module? 🙏

**Comment by AlbertMitjans** [comment]
@astafan8 can you take a look at this PR? We would love to merge it this week 😄

**Review by astafan8 — APPROVED** [review]

**Comment by fedonman** [comment]
Hello @astafan8 and thanks for the approval. `build docs` action is failing with error `ValueError: Could not locate a VISA implementation. Install either the IVI binary or pyvisa-py.` I guess this has to do with the environment used in the action and not with the PR itself.

**Comment by astafan8** [comment]
@fedonman ah, indeed. So one needs to disable the execution of the example notebook during the docs build, see here for instructions https://qcodes.github.io/Qcodes/examples/writing_drivers/Creating-Instrument-Drivers.html#Documentation

**Comment by fedonman** [comment]
> @fedonman ah, indeed. So one needs to disable the execution of the example notebook during the docs build, see here for instructions https://qcodes.github.io/Qcodes/examples/writing_drivers/Creating-Instrument-Drivers.html#Documentation

@astafan8 Done, thank you. Could you run the workflow again?

**Comment by fedonman** [comment]
@astafan8 Hey, I think, GitHub doesn't like me and disabled the auto-merge 😆 

> auto-merge was automatically disabled [6 hours ago](https://github.com/QCoDeS/Qcodes_contrib_drivers/pull/270#event-11014571883)
> Head branch was pushed to by a user without write access

If you feel everything is in place, be free to merge this. Thanks!

**Pull request merged**
