### PR TITLE
Add Holzworth HS9008B, General Microwave GM349, and NI DAQ drivers

### PR DESCRIPTION
**Pull request by ty-zhao**
Slightly modified Holzworth HS900 driver so that it now works properly for Holzworth HS9008B signal generators. Modified National Instrument DAQ driver so that digital output devices can now be properly controlled. Tested with NI PXI-6509.

### CODE REVIEW

**Review by astafan8 — APPROVED** [review]

**Comment by simonzihlmann** [comment]
@ty-zhao May I ask what you had to change to make the driver working with the model HS9008B?

**Comment by ty-zhao** [comment]
> @ty-zhao May I ask what you had to change to make the driver working with the model HS9008B?

Just a minor change. On line 246 of the original HS900 driver, I changed `terminator='\n'` to `termintor=''`. The return strings of our HS9008B don't have '\n' as the line terminator. Using the original driver would cause a timeout error.

**Comment by simonzihlmann** [comment]
> Just a minor change. On line 246 of the original HS900 driver, I changed `terminator='\n'` to `termintor=''`. The return strings of our HS9008B don't have '\n' as the line terminator. Using the original driver would cause a timeout error.

I see. But for that you do not need to change the driver. You could just pass the terminator string (in your case "") in the init-function when you initialize your device, no?

**Comment by simonzihlmann** [comment]
I see. Well then I guess it is complicated to have a single file only.

**Pull request merged**
